<?php

namespace Database\Seeders;

use App\Models\PreparationTaskTemplate;
use Illuminate\Database\Seeder;

class PreparationTaskTemplateSeeder extends Seeder
{
    private array $templates = [

        // ──────────────────────────────────────────
        // LAMARAN
        // ──────────────────────────────────────────
        'lamaran' => [
            ['label' => 'Persiapan Umum',      'title' => 'Tentukan tanggal dan lokasi lamaran'],
            ['label' => 'Persiapan Umum',      'title' => 'Tentukan MC / pembawa acara'],
            ['label' => 'Persiapan Umum',      'title' => 'Susun rundown acara lamaran'],
            ['label' => 'Persiapan Umum',      'title' => 'Gladi resik prosesi lamaran'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Rapat koordinasi kedua keluarga'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Konfirmasi peran anggota keluarga'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Briefing keluarga sebelum hari-H'],
            ['label' => 'Tamu & Undangan',     'title' => 'Buat daftar tamu undangan lamaran'],
            ['label' => 'Tamu & Undangan',     'title' => 'Kirim undangan lamaran'],
            ['label' => 'Tamu & Undangan',     'title' => 'Konfirmasi kehadiran tamu'],
            ['label' => 'Seserahan',           'title' => 'Tentukan isi seserahan / hantaran'],
            ['label' => 'Seserahan',           'title' => 'Beli perlengkapan seserahan'],
            ['label' => 'Seserahan',           'title' => 'Kemas dan hias seserahan'],
            ['label' => 'Cincin Lamaran',      'title' => 'Pilih dan beli cincin lamaran'],
            ['label' => 'Cincin Lamaran',      'title' => 'Siapkan kotak / wadah cincin lamaran'],
            ['label' => 'Busana',              'title' => 'Pilih busana lamaran pengantin pria'],
            ['label' => 'Busana',              'title' => 'Pilih busana lamaran pengantin wanita'],
            ['label' => 'Busana',              'title' => 'Fitting busana lamaran'],
            ['label' => 'Aksesori & Perhiasan','title' => 'Siapkan aksesori pengantin wanita'],
            ['label' => 'Aksesori & Perhiasan','title' => 'Siapkan perhiasan untuk acara lamaran'],
            ['label' => 'Katering',            'title' => 'Pesan katering untuk acara lamaran'],
            ['label' => 'Katering',            'title' => 'Konfirmasi menu dan jumlah porsi'],
            ['label' => 'Konsumsi',            'title' => 'Siapkan snack / konsumsi ringan tamu'],
            ['label' => 'Konsumsi',            'title' => 'Konfirmasi jumlah konsumsi tamu'],
            ['label' => 'Dekorasi',            'title' => 'Tentukan tema dekorasi lamaran'],
            ['label' => 'Dekorasi',            'title' => 'Sewa / beli dekorasi tempat'],
            ['label' => 'Sound System',        'title' => 'Sewa / pinjam sound system'],
            ['label' => 'Sound System',        'title' => 'Cek dan uji sound system'],
            ['label' => 'Transportasi',        'title' => 'Siapkan transportasi keluarga pengantin'],
            ['label' => 'Transportasi',        'title' => 'Koordinasi parkir tamu'],
            ['label' => 'Dokumentasi',         'title' => 'Booking fotografer lamaran'],
            ['label' => 'Dokumentasi',         'title' => 'Briefing konsep foto dengan fotografer'],
            ['label' => 'Dokumen',             'title' => 'Siapkan surat pernyataan / dokumen lamaran'],
            ['label' => 'Dokumen',             'title' => 'Tanda tangan dokumen persetujuan'],
            ['label' => 'Keuangan',            'title' => 'Buat anggaran acara lamaran'],
            ['label' => 'Keuangan',            'title' => 'Lunasi pembayaran semua vendor'],
        ],

        // ──────────────────────────────────────────
        // PENGAJIAN
        // ──────────────────────────────────────────
        'pengajian' => [
            ['label' => 'Persiapan Umum',      'title' => 'Konfirmasi jadwal dan lokasi pengajian'],
            ['label' => 'Persiapan Umum',      'title' => 'Konfirmasi jumlah tamu pengajian'],
            ['label' => 'Persiapan Umum',      'title' => 'Susun rundown acara pengajian'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Koordinasi dengan keluarga penyelenggara'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Briefing panitia pengajian'],
            ['label' => 'Tamu & Undangan',     'title' => 'Buat daftar tamu pengajian'],
            ['label' => 'Tamu & Undangan',     'title' => 'Kirim undangan pengajian'],
            ['label' => 'Tamu & Undangan',     'title' => 'Konfirmasi kehadiran tamu'],
            ['label' => 'Pemimpin Acara',      'title' => 'Undang ustadz / kyai'],
            ['label' => 'Pemimpin Acara',      'title' => 'Konfirmasi materi dan jadwal ceramah'],
            ['label' => 'Pemimpin Acara',      'title' => 'Siapkan honorarium ustadz / kyai'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan Al-Quran dan perlengkapan'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan buku yasin untuk tamu'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan sajadah dan perlengkapan shalat'],
            ['label' => 'Konsumsi',            'title' => 'Pesan konsumsi untuk tamu pengajian'],
            ['label' => 'Konsumsi',            'title' => 'Konfirmasi jumlah porsi konsumsi'],
            ['label' => 'Dekorasi',            'title' => 'Siapkan dekorasi ruangan pengajian'],
            ['label' => 'Dekorasi',            'title' => 'Pasang backdrop / spanduk acara'],
            ['label' => 'Sound System',        'title' => 'Sewa / pinjam sound system'],
            ['label' => 'Sound System',        'title' => 'Cek dan uji sound system'],
            ['label' => 'Busana',              'title' => 'Siapkan busana pengajian (islami)'],
            ['label' => 'Busana',              'title' => 'Seragam panitia pengajian'],
            ['label' => 'Transportasi',        'title' => 'Siapkan transportasi pengisi acara'],
            ['label' => 'Dokumentasi',         'title' => 'Booking fotografer pengajian'],
            ['label' => 'Dokumentasi',         'title' => 'Dokumentasi foto dan video acara'],
            ['label' => 'Hadiah & Souvenir',   'title' => 'Siapkan souvenir / kenang-kenangan tamu'],
            ['label' => 'Hadiah & Souvenir',   'title' => 'Kemas dan distribusi hadiah'],
            ['label' => 'Keuangan',            'title' => 'Buat anggaran acara pengajian'],
            ['label' => 'Keuangan',            'title' => 'Lunasi pembayaran semua vendor'],
        ],

        // ──────────────────────────────────────────
        // AKAD
        // ──────────────────────────────────────────
        'akad' => [
            ['label' => 'Dokumen Nikah',       'title' => 'Urus surat nikah di KUA'],
            ['label' => 'Dokumen Nikah',       'title' => 'Lengkapi berkas administrasi nikah'],
            ['label' => 'Dokumen Nikah',       'title' => 'Konfirmasi jadwal dengan KUA / penghulu'],
            ['label' => 'KUA & Administrasi',  'title' => 'Daftar di KUA setempat'],
            ['label' => 'KUA & Administrasi',  'title' => 'Bayar biaya pencatatan nikah'],
            ['label' => 'KUA & Administrasi',  'title' => 'Ambil buku nikah setelah akad'],
            ['label' => 'Perizinan',           'title' => 'Izin RT/RW setempat untuk acara'],
            ['label' => 'Perizinan',           'title' => 'Koordinasi dengan kelurahan jika perlu'],
            ['label' => 'Penghulu & Wali',     'title' => 'Konfirmasi penghulu / wali nikah'],
            ['label' => 'Penghulu & Wali',     'title' => 'Briefing teknis dengan penghulu'],
            ['label' => 'Penghulu & Wali',     'title' => 'Siapkan honorarium penghulu'],
            ['label' => 'Koordinasi Saksi',    'title' => 'Pilih dan konfirmasi dua saksi akad'],
            ['label' => 'Koordinasi Saksi',    'title' => 'Briefing saksi sebelum akad'],
            ['label' => 'Ijab Kabul',          'title' => 'Latihan ijab kabul'],
            ['label' => 'Ijab Kabul',          'title' => 'Hafalkan kalimat ijab kabul'],
            ['label' => 'Prosesi Akad',        'title' => 'Konfirmasi lokasi dan waktu akad nikah'],
            ['label' => 'Prosesi Akad',        'title' => 'Susun urutan prosesi akad'],
            ['label' => 'Prosesi Akad',        'title' => 'Gladi resik keseluruhan prosesi akad'],
            ['label' => 'Rundown Acara',       'title' => 'Buat rundown detail acara akad'],
            ['label' => 'Rundown Acara',       'title' => 'Briefing MC dan panitia akad'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan Al-Quran dan perlengkapan akad'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan sajadah dan perlengkapan shalat'],
            ['label' => 'Perlengkapan Ibadah', 'title' => 'Siapkan tasbih / perlengkapan ibadah'],
            ['label' => 'Persiapan Spiritual', 'title' => 'Konsultasi dengan ustadz / tokoh agama'],
            ['label' => 'Persiapan Spiritual', 'title' => 'Perbanyak ibadah dan doa sebelum akad'],
            ['label' => 'Persiapan Spiritual', 'title' => 'Shalat hajat menjelang hari akad'],
            ['label' => 'Mahar',               'title' => 'Tentukan jenis mahar'],
            ['label' => 'Mahar',               'title' => 'Siapkan / beli mahar (mas kawin)'],
            ['label' => 'Mahar',               'title' => 'Hias mahar untuk ditampilkan saat akad'],
            ['label' => 'Cincin Nikah',        'title' => 'Pilih dan beli cincin nikah sepasang'],
            ['label' => 'Cincin Nikah',        'title' => 'Siapkan kotak cincin'],
            ['label' => 'Aksesori & Perhiasan','title' => 'Siapkan aksesori pengantin wanita'],
            ['label' => 'Aksesori & Perhiasan','title' => 'Siapkan perhiasan untuk akad'],
            ['label' => 'Lokasi & Venue',      'title' => 'Konfirmasi lokasi akad nikah'],
            ['label' => 'Lokasi & Venue',      'title' => 'Survei dan cek kesiapan tempat'],
            ['label' => 'Lokasi & Venue',      'title' => 'Koordinasi tata letak ruangan'],
            ['label' => 'Pelaminan',           'title' => 'Booking dekorasi pelaminan akad'],
            ['label' => 'Pelaminan',           'title' => 'Konfirmasi setup pelaminan sebelum hari-H'],
            ['label' => 'Dekorasi',            'title' => 'Tentukan konsep dekorasi akad'],
            ['label' => 'Dekorasi',            'title' => 'Konfirmasi detail dekorasi dengan vendor'],
            ['label' => 'Konsumsi',            'title' => 'Pesan konsumsi untuk tamu akad'],
            ['label' => 'Konsumsi',            'title' => 'Konfirmasi jumlah porsi konsumsi'],
            ['label' => 'Tamu & Undangan',     'title' => 'Buat daftar tamu akad'],
            ['label' => 'Tamu & Undangan',     'title' => 'Kirim undangan akad'],
            ['label' => 'Tamu & Undangan',     'title' => 'Konfirmasi kehadiran tamu akad'],
            ['label' => 'Akomodasi Tamu',      'title' => 'Koordinasi hotel untuk tamu luar kota'],
            ['label' => 'Akomodasi Tamu',      'title' => 'Siapkan petunjuk arah lokasi akad'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Briefing seluruh anggota keluarga'],
            ['label' => 'Koordinasi Keluarga', 'title' => 'Koordinasi prosesi penyambutan'],
            ['label' => 'Busana Pengantin',    'title' => 'Pilih busana akad pengantin wanita'],
            ['label' => 'Busana Pengantin',    'title' => 'Pilih busana akad pengantin pria'],
            ['label' => 'Busana Pengantin',    'title' => 'Fitting busana akad'],
            ['label' => 'Busana & MUA',        'title' => 'Booking makeup artist (MUA) akad'],
            ['label' => 'Busana & MUA',        'title' => 'Trial makeup akad'],
            ['label' => 'Busana & MUA',        'title' => 'Konfirmasi jadwal MUA hari-H akad'],
            ['label' => 'Kesehatan & Kecantikan','title' => 'Perawatan wajah sebelum akad'],
            ['label' => 'Kesehatan & Kecantikan','title' => 'Perawatan rambut / creambath'],
            ['label' => 'Kesehatan & Kecantikan','title' => 'Istirahat cukup menjelang hari-H'],
            ['label' => 'Sound System',        'title' => 'Sewa sound system akad'],
            ['label' => 'Sound System',        'title' => 'Cek dan uji sound system sebelum akad'],
            ['label' => 'Transportasi',        'title' => 'Siapkan transportasi pengantin'],
            ['label' => 'Transportasi',        'title' => 'Koordinasi parkir tamu akad'],
            ['label' => 'Pre-Wedding',         'title' => 'Sesi foto prewedding'],
            ['label' => 'Pre-Wedding',         'title' => 'Edit dan cetak foto prewedding'],
            ['label' => 'Dokumentasi',         'title' => 'Booking fotografer & videografer akad'],
            ['label' => 'Dokumentasi',         'title' => 'Briefing alur foto saat akad'],
            ['label' => 'Dokumentasi',         'title' => 'Pelunasan fotografer'],
            ['label' => 'Koordinasi WO',       'title' => 'Briefing wedding organizer'],
            ['label' => 'Koordinasi WO',       'title' => 'Konfirmasi rundown dengan WO'],
            ['label' => 'Keuangan',            'title' => 'Buat anggaran acara akad'],
            ['label' => 'Keuangan',            'title' => 'Catat semua pembayaran vendor'],
            ['label' => 'Keuangan',            'title' => 'Lunasi semua vendor akad'],
        ],

        // ──────────────────────────────────────────
        // RESEPSI
        // ──────────────────────────────────────────
        'resepsi' => [
            ['label' => 'Venue & Gedung',          'title' => 'Survey dan pilih venue resepsi'],
            ['label' => 'Venue & Gedung',          'title' => 'Tanda tangan kontrak venue'],
            ['label' => 'Venue & Gedung',          'title' => 'Bayar DP venue'],
            ['label' => 'Venue & Gedung',          'title' => 'Konfirmasi kapasitas dan layout venue'],
            ['label' => 'Venue & Gedung',          'title' => 'Pelunasan biaya venue'],
            ['label' => 'Tenda & Fasilitas',       'title' => 'Sewa tenda untuk area outdoor'],
            ['label' => 'Tenda & Fasilitas',       'title' => 'Konfirmasi meja dan kursi'],
            ['label' => 'Tenda & Fasilitas',       'title' => 'Cek ketersediaan fasilitas venue'],
            ['label' => 'Perizinan',               'title' => 'Izin RT/RW dan kelurahan'],
            ['label' => 'Perizinan',               'title' => 'Koordinasi dengan keamanan setempat'],
            ['label' => 'Perizinan',               'title' => 'Izin penggunaan jalan jika diperlukan'],
            ['label' => 'Listrik & Generator',     'title' => 'Cek ketersediaan listrik venue'],
            ['label' => 'Listrik & Generator',     'title' => 'Sewa genset sebagai backup'],
            ['label' => 'Parkir & Keamanan',       'title' => 'Koordinasi area parkir tamu'],
            ['label' => 'Parkir & Keamanan',       'title' => 'Sewa jasa keamanan / security'],
            ['label' => 'Parkir & Keamanan',       'title' => 'Buat sistem penomoran parkir'],
            ['label' => 'Kebersihan',              'title' => 'Koordinasi kebersihan sebelum acara'],
            ['label' => 'Kebersihan',              'title' => 'Koordinasi kebersihan setelah acara'],
            ['label' => 'Toilet & Fasilitas',      'title' => 'Pastikan jumlah toilet mencukupi'],
            ['label' => 'Toilet & Fasilitas',      'title' => 'Sewa toilet portable jika perlu'],
            ['label' => 'Pelaminan',               'title' => 'Booking vendor dekorasi pelaminan'],
            ['label' => 'Pelaminan',               'title' => 'Konfirmasi konsep pelaminan'],
            ['label' => 'Pelaminan',               'title' => 'Final cek pelaminan sebelum hari-H'],
            ['label' => 'Dekorasi',                'title' => 'Pilih tema dan konsep dekorasi'],
            ['label' => 'Dekorasi',                'title' => 'Konfirmasi dekorasi dengan vendor'],
            ['label' => 'Dekorasi',                'title' => 'Final fitting dekorasi sebelum hari-H'],
            ['label' => 'Dekorasi Pintu Masuk',    'title' => 'Desain gapura / arch pintu masuk'],
            ['label' => 'Dekorasi Pintu Masuk',    'title' => 'Siapkan standing flower / backdrop entrance'],
            ['label' => 'Dekorasi Meja',           'title' => 'Tentukan centerpiece meja tamu'],
            ['label' => 'Dekorasi Meja',           'title' => 'Konfirmasi detail dekorasi meja'],
            ['label' => 'Bunga & Rangkaian',       'title' => 'Pilih jenis bunga dekorasi'],
            ['label' => 'Bunga & Rangkaian',       'title' => 'Booking vendor bunga'],
            ['label' => 'Bunga & Rangkaian',       'title' => 'Konfirmasi rangkaian bunga sebelum hari-H'],
            ['label' => 'Katering',                'title' => 'Pilih vendor katering'],
            ['label' => 'Katering',                'title' => 'Food tasting dengan vendor katering'],
            ['label' => 'Katering',                'title' => 'Konfirmasi menu final'],
            ['label' => 'Katering',                'title' => 'Konfirmasi jumlah porsi katering'],
            ['label' => 'Katering',                'title' => 'Pelunasan katering'],
            ['label' => 'Konsumsi VIP',            'title' => 'Siapkan meja VIP dengan menu spesial'],
            ['label' => 'Konsumsi VIP',            'title' => 'Konfirmasi layanan untuk tamu VIP'],
            ['label' => 'Konsumsi Panitia',        'title' => 'Siapkan konsumsi panitia dan tim vendor'],
            ['label' => 'Konsumsi Panitia',        'title' => 'Pastikan konsumsi tersedia sepanjang acara'],
            ['label' => 'Undangan',                'title' => 'Desain undangan pernikahan'],
            ['label' => 'Undangan',                'title' => 'Cetak undangan fisik'],
            ['label' => 'Undangan',                'title' => 'Distribusi undangan fisik'],
            ['label' => 'Undangan',                'title' => 'Buat daftar penerima undangan'],
            ['label' => 'Undangan Digital',        'title' => 'Buat undangan digital / e-invite'],
            ['label' => 'Undangan Digital',        'title' => 'Kirim undangan digital via WA / media sosial'],
            ['label' => 'Undangan Digital',        'title' => 'Konfirmasi kehadiran via undangan digital'],
            ['label' => 'Tamu & Konfirmasi',       'title' => 'Buat daftar lengkap tamu undangan'],
            ['label' => 'Tamu & Konfirmasi',       'title' => 'Konfirmasi kehadiran tamu'],
            ['label' => 'Tamu & Konfirmasi',       'title' => 'Update jumlah tamu yang hadir ke katering'],
            ['label' => 'Penerima Tamu',           'title' => 'Tentukan petugas penerima tamu'],
            ['label' => 'Penerima Tamu',           'title' => 'Briefing penerima tamu'],
            ['label' => 'Penerima Tamu',           'title' => 'Siapkan buku tamu dan alat tulis'],
            ['label' => 'Dress Code Tamu',         'title' => 'Tentukan dress code tamu'],
            ['label' => 'Dress Code Tamu',         'title' => 'Cantumkan dress code di undangan'],
            ['label' => 'Akomodasi Tamu',          'title' => 'Koordinasi hotel untuk tamu dari luar kota'],
            ['label' => 'Akomodasi Tamu',          'title' => 'Siapkan petunjuk arah ke venue'],
            ['label' => 'Souvenir',                'title' => 'Pilih jenis souvenir tamu'],
            ['label' => 'Souvenir',                'title' => 'Pesan souvenir tamu'],
            ['label' => 'Souvenir',                'title' => 'Kemas souvenir sebelum hari-H'],
            ['label' => 'Doorprize',               'title' => 'Siapkan doorprize untuk tamu'],
            ['label' => 'Doorprize',               'title' => 'Tentukan mekanisme pembagian doorprize'],
            ['label' => 'Busana & MUA',            'title' => 'Pilih gaun pengantin wanita'],
            ['label' => 'Busana & MUA',            'title' => 'Fitting gaun pengantin'],
            ['label' => 'Busana & MUA',            'title' => 'Pilih busana pengantin pria'],
            ['label' => 'Busana & MUA',            'title' => 'Booking makeup artist (MUA)'],
            ['label' => 'Busana & MUA',            'title' => 'Trial makeup'],
            ['label' => 'Aksesori & Perhiasan',    'title' => 'Siapkan aksesori dan perhiasan pengantin'],
            ['label' => 'Aksesori & Perhiasan',    'title' => 'Siapkan headpiece / mahkota pengantin'],
            ['label' => 'Kesehatan & Kecantikan',  'title' => 'Perawatan wajah dan kulit sebelum resepsi'],
            ['label' => 'Kesehatan & Kecantikan',  'title' => 'Perawatan rambut / creambath'],
            ['label' => 'Kesehatan & Kecantikan',  'title' => 'Istirahat cukup menjelang hari-H'],
            ['label' => 'Pre-Wedding',             'title' => 'Sesi foto prewedding'],
            ['label' => 'Pre-Wedding',             'title' => 'Edit dan cetak foto prewedding'],
            ['label' => 'Pre-Wedding',             'title' => 'Display foto di venue'],
            ['label' => 'Dokumentasi',             'title' => 'Booking fotografer & videografer resepsi'],
            ['label' => 'Dokumentasi',             'title' => 'Briefing konsep foto hari-H'],
            ['label' => 'Dokumentasi',             'title' => 'Pelunasan fotografer'],
            ['label' => 'Dokumentasi',             'title' => 'Edit dan delivery foto / video'],
            ['label' => 'Photo Booth',             'title' => 'Sewa / buat photo booth'],
            ['label' => 'Photo Booth',             'title' => 'Siapkan properti foto booth'],
            ['label' => 'Acara & MC',              'title' => 'Booking MC resepsi'],
            ['label' => 'Acara & MC',              'title' => 'Susun rundown acara resepsi'],
            ['label' => 'Acara & MC',              'title' => 'Briefing MC dan panitia'],
            ['label' => 'Acara & MC',              'title' => 'Gladi resik prosesi resepsi'],
            ['label' => 'Hiburan',                 'title' => 'Tentukan jenis hiburan (tari, drama, dll.)'],
            ['label' => 'Hiburan',                 'title' => 'Booking pengisi hiburan'],
            ['label' => 'Hiburan',                 'title' => 'Briefing pengisi hiburan'],
            ['label' => 'Live Music / Band',       'title' => 'Booking band / penyanyi'],
            ['label' => 'Live Music / Band',       'title' => 'Konfirmasi setlist lagu'],
            ['label' => 'Live Music / Band',       'title' => 'Sound check sebelum acara'],
            ['label' => 'Sound System & Lighting', 'title' => 'Booking vendor sound system'],
            ['label' => 'Sound System & Lighting', 'title' => 'Cek dan uji audio sebelum acara'],
            ['label' => 'Sound System & Lighting', 'title' => 'Konfirmasi tata cahaya venue'],
            ['label' => 'Transportasi',            'title' => 'Siapkan transportasi pengantin (mobil hias)'],
            ['label' => 'Transportasi',            'title' => 'Koordinasi parkir tamu resepsi'],
            ['label' => 'Transportasi',            'title' => 'Siapkan shuttle tamu jika diperlukan'],
            ['label' => 'Koordinasi Keluarga',     'title' => 'Briefing seluruh anggota keluarga'],
            ['label' => 'Koordinasi Keluarga',     'title' => 'Koordinasi prosesi penyambutan'],
            ['label' => 'Koordinasi Keluarga',     'title' => 'Tentukan posisi duduk keluarga'],
            ['label' => 'Koordinasi Vendor',       'title' => 'Buat daftar kontak semua vendor'],
            ['label' => 'Koordinasi Vendor',       'title' => 'Briefing seluruh vendor H-1'],
            ['label' => 'Koordinasi WO',           'title' => 'Briefing wedding organizer'],
            ['label' => 'Koordinasi WO',           'title' => 'Konfirmasi rundown dengan WO'],
            ['label' => 'Koordinasi WO',           'title' => 'Final meeting H-1 bersama WO'],
            ['label' => 'Koordinasi Katering',     'title' => 'Koordinasi jadwal serving katering'],
            ['label' => 'Koordinasi Katering',     'title' => 'Konfirmasi petugas katering hari-H'],
            ['label' => 'Pembayaran',              'title' => 'Buat daftar tagihan semua vendor'],
            ['label' => 'Pembayaran',              'title' => 'Bayar DP semua vendor'],
            ['label' => 'Pembayaran',              'title' => 'Pelunasan semua vendor resepsi'],
            ['label' => 'Keuangan',                'title' => 'Buat anggaran resepsi lengkap'],
            ['label' => 'Keuangan',                'title' => 'Monitor pengeluaran vs. anggaran'],
            ['label' => 'Keuangan',                'title' => 'Catat semua bukti pembayaran'],
            ['label' => 'Honeymoon',               'title' => 'Tentukan destinasi honeymoon'],
            ['label' => 'Honeymoon',               'title' => 'Booking hotel dan transportasi honeymoon'],
            ['label' => 'Honeymoon',               'title' => 'Siapkan keperluan dan dokumen honeymoon'],
        ],
    ];

    public function run(): void
    {
        PreparationTaskTemplate::truncate();

        foreach ($this->templates as $jenis => $tasks) {
            foreach ($tasks as $sort => $task) {
                PreparationTaskTemplate::create([
                    'jenis_acara' => $jenis,
                    'label'       => $task['label'],
                    'title'       => $task['title'],
                    'sort_order'  => $sort + 1,
                ]);
            }
        }

        $total = PreparationTaskTemplate::count();
        $this->command->info("PreparationTaskTemplateSeeder: {$total} template tugas berhasil dibuat.");

        $this->command->table(
            ['Jenis Acara', 'Jumlah Template'],
            collect($this->templates)->map(fn ($tasks, $jenis) => [
                ucfirst($jenis), count($tasks),
            ])->values()->toArray()
        );
    }
}
