<?php

namespace App\Enums;

enum ProvinsiEnum: string
{
    case DKI_JAKARTA = 'DKI Jakarta';
    case JAWA_BARAT = 'Jawa Barat';
    case JAWA_TENGAH = 'Jawa Tengah';
    case JAWA_TIMUR = 'Jawa Timur';
    case DAERAH_ISTIMEWA_YOGYAKARTA = 'DI Yogyakarta';
    case BANTEN = 'Banten';
    case BALI = 'Bali';
    case SUMATERA_UTARA = 'Sumatera Utara';
    case SUMATERA_BARAT = 'Sumatera Barat';
    case SUMATERA_SELATAN = 'Sumatera Selatan';
    case RIAU = 'Riau';
    case KEPULAUAN_RIAU = 'Kepulauan Riau';
    case JAMBI = 'Jambi';
    case BENGKULU = 'Bengkulu';
    case LAMPUNG = 'Lampung';
    case BANGKA_BELITUNG = 'Bangka Belitung';
    case ACEH = 'Aceh';
    case KALIMANTAN_BARAT = 'Kalimantan Barat';
    case KALIMANTAN_TENGAH = 'Kalimantan Tengah';
    case KALIMANTAN_SELATAN = 'Kalimantan Selatan';
    case KALIMANTAN_TIMUR = 'Kalimantan Timur';
    case KALIMANTAN_UTARA = 'Kalimantan Utara';
    case SULAWESI_UTARA = 'Sulawesi Utara';
    case SULAWESI_TENGAH = 'Sulawesi Tengah';
    case SULAWESI_SELATAN = 'Sulawesi Selatan';
    case SULAWESI_TENGGARA = 'Sulawesi Tenggara';
    case SULAWESI_BARAT = 'Sulawesi Barat';
    case GORONTALO = 'Gorontalo';
    case MALUKU = 'Maluku';
    case MALUKU_UTARA = 'Maluku Utara';
    case PAPUA = 'Papua';
    case PAPUA_BARAT = 'Papua Barat';
    case PAPUA_TENGAH = 'Papua Tengah';
    case PAPUA_PEGUNUNGAN = 'Papua Pegunungan';
    case PAPUA_SELATAN = 'Papua Selatan';
    case PAPUA_BARAT_DAYA = 'Papua Barat Daya';
    case NUSA_TENGGARA_BARAT = 'Nusa Tenggara Barat';
    case NUSA_TENGGARA_TIMUR = 'Nusa Tenggara Timur';

    public static function toArray(): array
    {
        return array_column(self::cases(), 'value', 'value');
    }

    public static function getKotaKabupaten(string $provinsi): array
    {
        return match($provinsi) {
            self::DKI_JAKARTA->value => [
                'Jakarta Pusat',
                'Jakarta Utara',
                'Jakarta Barat',
                'Jakarta Selatan',
                'Jakarta Timur',
                'Kepulauan Seribu',
            ],
            self::JAWA_BARAT->value => [
                'Bandung',
                'Bekasi',
                'Bogor',
                'Cirebon',
                'Depok',
                'Sukabumi',
                'Tasikmalaya',
                'Banjar',
                'Cimahi',
                'Bandung Barat',
                'Ciamis',
                'Cianjur',
                'Garut',
                'Indramayu',
                'Karawang',
                'Kuningan',
                'Majalengka',
                'Pangandaran',
                'Purwakarta',
                'Subang',
                'Sumedang',
            ],
            self::JAWA_TENGAH->value => [
                'Semarang',
                'Surakarta (Solo)',
                'Magelang',
                'Pekalongan',
                'Salatiga',
                'Tegal',
                'Banyumas',
                'Batang',
                'Blora',
                'Boyolali',
                'Brebes',
                'Cilacap',
                'Demak',
                'Grobogan',
                'Jepara',
                'Karanganyar',
                'Kebumen',
                'Kendal',
                'Klaten',
                'Kudus',
                'Pati',
                'Pemalang',
                'Purbalingga',
                'Purworejo',
                'Rembang',
                'Semarang (Kab)',
                'Sragen',
                'Sukoharjo',
                'Temanggung',
                'Wonogiri',
                'Wonosobo',
            ],
            self::JAWA_TIMUR->value => [
                'Surabaya',
                'Malang',
                'Kediri',
                'Madiun',
                'Mojokerto',
                'Pasuruan',
                'Probolinggo',
                'Blitar',
                'Batu',
                'Bangkalan',
                'Banyuwangi',
                'Bojonegoro',
                'Bondowoso',
                'Gresik',
                'Jember',
                'Jombang',
                'Lamongan',
                'Lumajang',
                'Magetan',
                'Nganjuk',
                'Ngawi',
                'Pacitan',
                'Pamekasan',
                'Ponorogo',
                'Sampang',
                'Sidoarjo',
                'Situbondo',
                'Sumenep',
                'Trenggalek',
                'Tuban',
                'Tulungagung',
            ],
            self::DAERAH_ISTIMEWA_YOGYAKARTA->value => [
                'Yogyakarta',
                'Bantul',
                'Gunungkidul',
                'Kulon Progo',
                'Sleman',
            ],
            self::BANTEN->value => [
                'Tangerang',
                'Tangerang Selatan',
                'Serang',
                'Cilegon',
                'Lebak',
                'Pandeglang',
                'Tangerang (Kab)',
            ],
            self::BALI->value => [
                'Denpasar',
                'Badung',
                'Bangli',
                'Buleleng',
                'Gianyar',
                'Jembrana',
                'Karangasem',
                'Klungkung',
                'Tabanan',
            ],
            self::SUMATERA_UTARA->value => [
                'Medan',
                'Binjai',
                'Padangsidimpuan',
                'Pematangsiantar',
                'Sibolga',
                'Tanjungbalai',
                'Tebing Tinggi',
                'Asahan',
                'Batubara',
                'Dairi',
                'Deli Serdang',
                'Humbang Hasundutan',
                'Karo',
                'Labuhanbatu',
                'Labuhanbatu Selatan',
                'Labuhanbatu Utara',
                'Langkat',
                'Mandailing Natal',
                'Nias',
                'Nias Barat',
                'Nias Selatan',
                'Nias Utara',
                'Padang Lawas',
                'Padang Lawas Utara',
                'Pakpak Bharat',
                'Samosir',
                'Serdang Bedagai',
                'Simalungun',
                'Tapanuli Selatan',
                'Tapanuli Tengah',
                'Tapanuli Utara',
                'Toba',
            ],
            self::SUMATERA_BARAT->value => [
                'Padang',
                'Bukittinggi',
                'Padangpanjang',
                'Pariaman',
                'Payakumbuh',
                'Sawahlunto',
                'Solok',
                'Agam',
                'Dharmasraya',
                'Kepulauan Mentawai',
                'Lima Puluh Kota',
                'Pasaman',
                'Pasaman Barat',
                'Pesisir Selatan',
                'Sijunjung',
                'Solok (Kab)',
                'Solok Selatan',
                'Tanah Datar',
            ],
            self::SUMATERA_SELATAN->value => [
                'Palembang',
                'Lubuklinggau',
                'Pagar Alam',
                'Prabumulih',
                'Banyuasin',
                'Empat Lawang',
                'Lahat',
                'Muara Enim',
                'Musi Banyuasin',
                'Musi Rawas',
                'Musi Rawas Utara',
                'Ogan Ilir',
                'Ogan Komering Ilir',
                'Ogan Komering Ulu',
                'Ogan Komering Ulu Selatan',
                'Ogan Komering Ulu Timur',
                'Penukal Abab Lematang Ilir',
            ],
            self::RIAU->value => [
                'Pekanbaru',
                'Dumai',
                'Bengkalis',
                'Indragiri Hilir',
                'Indragiri Hulu',
                'Kampar',
                'Kepulauan Meranti',
                'Kuantan Singingi',
                'Pelalawan',
                'Rokan Hilir',
                'Rokan Hulu',
                'Siak',
            ],
            self::KEPULAUAN_RIAU->value => [
                'Batam',
                'Tanjungpinang',
                'Bintan',
                'Karimun',
                'Kepulauan Anambas',
                'Lingga',
                'Natuna',
            ],
            self::JAMBI->value => [
                'Jambi',
                'Sungai Penuh',
                'Batanghari',
                'Bungo',
                'Kerinci',
                'Merangin',
                'Muaro Jambi',
                'Sarolangun',
                'Tanjung Jabung Barat',
                'Tanjung Jabung Timur',
                'Tebo',
            ],
            self::BENGKULU->value => [
                'Bengkulu',
                'Bengkulu Selatan',
                'Bengkulu Tengah',
                'Bengkulu Utara',
                'Kaur',
                'Kepahiang',
                'Lebong',
                'Mukomuko',
                'Rejang Lebong',
                'Seluma',
            ],
            self::LAMPUNG->value => [
                'Bandar Lampung',
                'Metro',
                'Lampung Barat',
                'Lampung Selatan',
                'Lampung Tengah',
                'Lampung Timur',
                'Lampung Utara',
                'Mesuji',
                'Pesawaran',
                'Pesisir Barat',
                'Pringsewu',
                'Tanggamus',
                'Tulang Bawang',
                'Tulang Bawang Barat',
                'Way Kanan',
            ],
            self::BANGKA_BELITUNG->value => [
                'Pangkalpinang',
                'Bangka',
                'Bangka Barat',
                'Bangka Selatan',
                'Bangka Tengah',
                'Belitung',
                'Belitung Timur',
            ],
            self::ACEH->value => [
                'Banda Aceh',
                'Langsa',
                'Lhokseumawe',
                'Sabang',
                'Subulussalam',
                'Aceh Barat',
                'Aceh Barat Daya',
                'Aceh Besar',
                'Aceh Jaya',
                'Aceh Selatan',
                'Aceh Singkil',
                'Aceh Tamiang',
                'Aceh Tengah',
                'Aceh Tenggara',
                'Aceh Timur',
                'Aceh Utara',
                'Bener Meriah',
                'Bireuen',
                'Gayo Lues',
                'Nagan Raya',
                'Pidie',
                'Pidie Jaya',
                'Simeulue',
            ],
            self::KALIMANTAN_BARAT->value => [
                'Pontianak',
                'Singkawang',
                'Bengkayang',
                'Kapuas Hulu',
                'Kayong Utara',
                'Ketapang',
                'Kubu Raya',
                'Landak',
                'Melawi',
                'Mempawah',
                'Sambas',
                'Sanggau',
                'Sekadau',
                'Sintang',
            ],
            self::KALIMANTAN_TENGAH->value => [
                'Palangkaraya',
                'Barito Selatan',
                'Barito Timur',
                'Barito Utara',
                'Gunung Mas',
                'Kapuas',
                'Katingan',
                'Kotawaringin Barat',
                'Kotawaringin Timur',
                'Lamandau',
                'Murung Raya',
                'Pulang Pisau',
                'Seruyan',
                'Sukamara',
            ],
            self::KALIMANTAN_SELATAN->value => [
                'Banjarmasin',
                'Banjarbaru',
                'Balangan',
                'Banjar',
                'Barito Kuala',
                'Hulu Sungai Selatan',
                'Hulu Sungai Tengah',
                'Hulu Sungai Utara',
                'Kotabaru',
                'Tabalong',
                'Tanah Bumbu',
                'Tanah Laut',
                'Tapin',
            ],
            self::KALIMANTAN_TIMUR->value => [
                'Balikpapan',
                'Bontang',
                'Samarinda',
                'Berau',
                'Kutai Barat',
                'Kutai Kartanegara',
                'Kutai Timur',
                'Mahakam Ulu',
                'Paser',
                'Penajam Paser Utara',
            ],
            self::KALIMANTAN_UTARA->value => [
                'Tarakan',
                'Bulungan',
                'Malinau',
                'Nunukan',
                'Tana Tidung',
            ],
            self::SULAWESI_UTARA->value => [
                'Manado',
                'Bitung',
                'Kotamobagu',
                'Tomohon',
                'Bolaang Mongondow',
                'Bolaang Mongondow Selatan',
                'Bolaang Mongondow Timur',
                'Bolaang Mongondow Utara',
                'Kepulauan Sangihe',
                'Kepulauan Siau Tagulandang Biaro',
                'Kepulauan Talaud',
                'Minahasa',
                'Minahasa Selatan',
                'Minahasa Tenggara',
                'Minahasa Utara',
            ],
            self::SULAWESI_TENGAH->value => [
                'Palu',
                'Banggai',
                'Banggai Kepulauan',
                'Banggai Laut',
                'Buol',
                'Donggala',
                'Morowali',
                'Morowali Utara',
                'Parigi Moutong',
                'Poso',
                'Sigi',
                'Tojo Una-Una',
                'Toli-Toli',
            ],
            self::SULAWESI_SELATAN->value => [
                'Makassar',
                'Palopo',
                'Parepare',
                'Bantaeng',
                'Barru',
                'Bone',
                'Bulukumba',
                'Enrekang',
                'Gowa',
                'Jeneponto',
                'Kepulauan Selayar',
                'Luwu',
                'Luwu Timur',
                'Luwu Utara',
                'Maros',
                'Pangkajene dan Kepulauan',
                'Pinrang',
                'Sidenreng Rappang',
                'Sinjai',
                'Soppeng',
                'Takalar',
                'Tana Toraja',
                'Toraja Utara',
                'Wajo',
            ],
            self::SULAWESI_TENGGARA->value => [
                'Kendari',
                'Baubau',
                'Bombana',
                'Buton',
                'Buton Selatan',
                'Buton Tengah',
                'Buton Utara',
                'Kolaka',
                'Kolaka Timur',
                'Kolaka Utara',
                'Konawe',
                'Konawe Kepulauan',
                'Konawe Selatan',
                'Konawe Utara',
                'Muna',
                'Muna Barat',
                'Wakatobi',
            ],
            self::SULAWESI_BARAT->value => [
                'Majene',
                'Mamasa',
                'Mamuju',
                'Mamuju Tengah',
                'Mamuju Utara',
                'Polewali Mandar',
            ],
            self::GORONTALO->value => [
                'Gorontalo',
                'Boalemo',
                'Bone Bolango',
                'Gorontalo (Kab)',
                'Gorontalo Utara',
                'Pohuwato',
            ],
            self::MALUKU->value => [
                'Ambon',
                'Tual',
                'Buru',
                'Buru Selatan',
                'Kepulauan Aru',
                'Maluku Barat Daya',
                'Maluku Tengah',
                'Maluku Tenggara',
                'Maluku Tenggara Barat',
                'Seram Bagian Barat',
                'Seram Bagian Timur',
            ],
            self::MALUKU_UTARA->value => [
                'Ternate',
                'Tidore Kepulauan',
                'Halmahera Barat',
                'Halmahera Selatan',
                'Halmahera Tengah',
                'Halmahera Timur',
                'Halmahera Utara',
                'Kepulauan Sula',
                'Pulau Morotai',
                'Pulau Taliabu',
            ],
            self::PAPUA->value => [
                'Jayapura',
                'Asmat',
                'Biak Numfor',
                'Boven Digoel',
                'Deiyai',
                'Dogiyai',
                'Intan Jaya',
                'Jayapura (Kab)',
                'Jayawijaya',
                'Keerom',
                'Kepulauan Yapen',
                'Lanny Jaya',
                'Mamberamo Raya',
                'Mamberamo Tengah',
                'Mappi',
                'Merauke',
                'Mimika',
                'Nabire',
                'Nduga',
                'Paniai',
                'Pegunungan Bintang',
                'Puncak',
                'Puncak Jaya',
                'Sarmi',
                'Supiori',
                'Tolikara',
                'Waropen',
                'Yahukimo',
                'Yalimo',
            ],
            self::PAPUA_BARAT->value => [
                'Manokwari',
                'Sorong',
                'Fakfak',
                'Kaimana',
                'Manokwari Selatan',
                'Maybrat',
                'Pegunungan Arfak',
                'Raja Ampat',
                'Sorong (Kab)',
                'Sorong Selatan',
                'Tambrauw',
                'Teluk Bintuni',
                'Teluk Wondama',
            ],
            self::PAPUA_TENGAH->value => [
                'Nabire',
                'Dogiyai',
                'Deiyai',
                'Intan Jaya',
                'Paniai',
                'Mimika',
            ],
            self::PAPUA_PEGUNUNGAN->value => [
                'Jayawijaya',
                'Lanny Jaya',
                'Mamberamo Tengah',
                'Nduga',
                'Pegunungan Bintang',
                'Puncak',
                'Puncak Jaya',
                'Tolikara',
                'Yahukimo',
                'Yalimo',
            ],
            self::PAPUA_SELATAN->value => [
                'Merauke',
                'Asmat',
                'Boven Digoel',
                'Mappi',
            ],
            self::PAPUA_BARAT_DAYA->value => [
                'Sorong',
                'Fakfak',
                'Kaimana',
                'Maybrat',
                'Raja Ampat',
                'Sorong (Kab)',
                'Sorong Selatan',
                'Tambrauw',
            ],
            self::NUSA_TENGGARA_BARAT->value => [
                'Mataram',
                'Bima',
                'Bima (Kab)',
                'Dompu',
                'Lombok Barat',
                'Lombok Tengah',
                'Lombok Timur',
                'Lombok Utara',
                'Sumbawa',
                'Sumbawa Barat',
            ],
            self::NUSA_TENGGARA_TIMUR->value => [
                'Kupang',
                'Alor',
                'Belu',
                'Ende',
                'Flores Timur',
                'Kupang (Kab)',
                'Lembata',
                'Malaka',
                'Manggarai',
                'Manggarai Barat',
                'Manggarai Timur',
                'Nagekeo',
                'Ngada',
                'Rote Ndao',
                'Sabu Raijua',
                'Sikka',
                'Sumba Barat',
                'Sumba Barat Daya',
                'Sumba Tengah',
                'Sumba Timur',
                'Timor Tengah Selatan',
                'Timor Tengah Utara',
            ],
            default => [],
        };
    }
}
